var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var l=0;return function(){return l<a.length?{done:!1,value:a[l++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var l="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return l?l.call(a):$jscomp.arrayIterator(a)};$jscomp.arrayFromIterator=function(a){for(var l,k=[];!(l=a.next()).done;)k.push(l.value);return k};
$jscomp.arrayFromIterable=function(a){return a instanceof Array?a:$jscomp.arrayFromIterator($jscomp.makeIterator(a))};
define("fonts-debugger",[],function(){return function(){function a(){h();[].concat($jscomp.arrayFromIterable(document.body.querySelectorAll("*"))).forEach(function(b){var a=[].concat($jscomp.arrayFromIterable(b.classList)).find(function(b){return b.startsWith(d.debugFonts)});a&&b.classList.remove(a)})}function l(d){d=void 0===d?"":d;var b=[].concat($jscomp.arrayFromIterable(document.body.querySelectorAll(p.relevantElements)));w=d?b.filter(function(b){return b.closest(d)}):b}function k(){A.map(function(b){var a=
d.debugFonts+"-"+b.join("-");b='\n                    \x3cstyle class\x3d"'+d.debugStyle+'"\x3e\n                        .'+a+" {\n                            position: relative;\n                        }\n                        ."+a+":after {\n                            position: absolute;\n                            content: '"+(""+b)+"';\n                            color: red;\n                            text-align: end;\n                            font-size: 12px;\n                            font-weight: 700;\n                            text-transform: uppercase;\n                            border: 2px solid currentColor;\n                            text-shadow: 0 0 4px rgba(255, 255, 255, 1), 0 0 8px rgba(255, 255, 255, 1), 0 0 12px rgba(255, 255, 255, 1);\n                            top: 0;\n                            right: 0;\n                            bottom: 0;\n                            left: 0;\n                        }\n                    \x3c/style\x3e\n                ";
a=document.createElement("template");b=b.trim();a.innerHTML=b;return a.content.firstChild}).forEach(function(b){return document.head.appendChild(b)})}function h(){document.head.querySelectorAll(d.debugStyle).forEach(function(b){return b.remove()})}function f(b){return Object.values(u).some(function(d){return parseInt(b.fontSize)===d})}function c(a){a=void 0===a?{}:a;var c=void 0===a.errorKeys?[]:a.errorKeys,g=void 0===a.printElements?!1:a.printElements;y=0;w.forEach(function(a){var n=[],p=getComputedStyle(a);
if([].concat($jscomp.arrayFromIterable(a.childNodes)).some(function(b){return 3===b.nodeType&&0<b.textContent.trim().length})){if(0===c.length||c.includes("family"))e(p.fontFamily)||n.push("family");if(0===c.length||c.includes("weight")){var t=parseInt(p.fontWeight);r.includes(t)||n.push("weight")}if(0===c.length||c.includes("size"))f(p)||n.push("size");if(0===c.length||c.includes("height"))b(a)||q(a)||Object.values(u).some(function(b){return parseInt(p.fontSize)===b})&&v.forEach(function(b){var d=
$jscomp.makeIterator(b);b=d.next().value;d=d.next().value;var a=parseInt(p.fontSize),c=parseInt(p.lineHeight);a===b&&c!==d&&n.push("height")});(0===c.length||c.includes("spacing"))&&"normal"!==p.letterSpacing&&0!==parseInt(p.letterSpacing)&&n.push("spacing");(0===c.length||c.includes("margin"))&&[p.marginTop,p.marginRight,p.marginBottom,p.marginLeft].some(function(b){return b.startsWith("-")})&&n.push("margin");if((0===c.length||c.includes("button"))&&b(a)){t=parseInt(p.fontSize);var m=parseInt(p.lineHeight);
16===t&&20===m||n.push("button")}0<n.length&&(y+=n.length,t=d.debugFonts+"-"+n.join("-"),a.classList.add(t),g&&console.log(a))}})}function b(b){if(!b)return!1;var d=getComputedStyle(b);b=parseInt(d.fontWeight);var a=parseInt(d.fontSize),c=parseInt(d.height);d=parseInt(d.width);return 700===b&&40<=c&&48<=d&&16===a}function q(d){return m(d,!0).some(function(d){return b(d)})}function m(b,d){for(var a=[];b&&(!d||"BODY"!==b.tagName);)a.unshift(b),b=b.parentElement;return a}function e(b){if(B){if(!n.rtl.includes(b))return!1}else if(g.includes(x)){if(!n.fallback[x].includes(b))return!1}else if(!b.includes(n.default))return!1;
return!0}var d={debugFonts:"debug-fonts",debugStyle:"debug-style"},p={debugFonts:"[class*\x3d"+d.debugFonts+"]",icons:"[class*\x3dicon-]",arrowButtons:"[class*\x3dbtn-arrow]"};p.relevantElements="*:not("+p.icons+"):not("+p.arrowButtons+"):not(script):not(body)";var n={default:"bmwTypeNextWeb",rtl:["bmwTypeWeb, Arial, Helvetica, sans-serif"],fallback:{"ja-JP":['bmwTypeWeb, Arial, Helvetica, "Noto Sans CJK JP", "Noto Sans", sans-serif'],"ko-KR":['bmwTypeWeb, Arial, Helvetica, "Noto Sans CJK KR", "Noto Sans", sans-serif'],
"zh-CN":['bmwTypeWeb, Arial, Helvetica, "Noto Sans CJK SC", "Noto Sans", sans-serif'],"zh-TW":['bmwTypeWeb, Arial, "microsoft jhenghei", Helvetica, "Noto Sans CJK TC", "Noto Sans", sans-serif'],"zh-HK":['bmwTypeWeb, Arial, "microsoft jhenghei", Helvetica, "Noto Sans CJK TC", "Noto Sans", sans-serif'],"th-TH":["bmwTypeWeb, Arial, Helvetica, sans-serif"],"vi-VN":["bmwTypeWeb, Arial, Helvetica, sans-serif"]}},g=Object.keys(n.fallback),r=[300,400,700],u={fs10:10,fs12:12,fs14:14,fs16:16,fs20:20,fs24:24,
fs32:32,fs48:48,fs64:64},v=[[10,14],[12,16],[14,20],[16,24],[20,28],[24,32],[32,40],[48,64],[64,80]],t={},z=(t.family='Invalid font-family. Valid value: "bmwTypeNextWeb" or "bmwTypeWeb" for special markets, see BMWWEB-33375',t.weight="Invalid font-weight. Valid values: "+r.join(", "),t.size="Invalid font-size. Valid values (px): "+Object.values(u).join(", "),t.height="Invalid line-height. Valid [font-size, line-height] pairs (in px):"+v.join(", "),t.spacing="Invalid letter-spacing. Valid value: 0",
t.margin="Invalid margin. Negative values are invalid.",t.button="Invalid button style. Valid values:\n                    font-size 16px, line-height 20px",t),A=function(b){var d=function(b,a,c){if(0!==b.length||0!==a.length)return 0===a.length?c.push(b):(d(b.concat(a[0]),a.slice(1),c),d(b,a.slice(1),c)),c};return d([],b,[])}(Object.keys(z)),B="rtl"===document.dir,x,w=[],y=0;window.fontsDebugger={showIssues:function(b){var d=void 0===b?{}:b;b=void 0===d.errorKeys?[]:d.errorKeys;var r=void 0===d.ancestor?
"":d.ancestor;d=void 0===d.printElements?!1:d.printElements;x=document.documentElement.lang;k();l(r);a();c({errorKeys:b,printElements:d});console.log("Number of errors: "+y);console.log("Sample usage with parameters: \nfontsDebugger.showIssues({errorKeys: ['family', 'size'], printElements: true, ancestor: '.my-component'});");console.log("Error keys:");console.table(z)},hideIssues:a}}});
define("ds2-uxn-navigation-utils",["fonts-debugger"],function(a){new a;a=function(){this.rtl="rtl"==$("html").attr("dir")};var l=a.prototype;l.isMobileLayout=function(){return 992>window.innerWidth};l.isExtendedTabletLayout=function(){return 1200>window.innerWidth};l.isRtl=function(){return this.rtl};l.getAnimationObject=function(a){return JSON.parse('{"'+this.getMarginProperty()+'": "'+a+'"}')};l.getMarginProperty=function(){return this.rtl?"margin-right":"margin-left"};l.isEventKeyCode=function(a,
h){return(a.keyCode?a.keyCode:a.which)!=h||a.shiftKey?!1:!0};l.isEventKeyCodeShift=function(a,h){return(a.keyCode?a.keyCode:a.which)==h&&a.shiftKey?!0:!1};l.focus=function(a){a&&0<a.length&&a.focus()};return new a});
define("ds2-uxn-allmodels-flyout",["jquery","ds2-uxn-navigation-utils"],function(a,l){var k=function(a){this.$component=a;this.$linksContainer=this.$component.find(".ds2-links-container");this.init()},h=k.prototype;h.setActionsHandler=function(a){this.actionsHandler=a};h.getTitle=function(){return this.$component.find(".ds2-flyout-nav-bar-data-holder").data("title")};h.showQuickActions=function(a){a=this.$component.find(".ds2-flyout-quickactions");this.actionsHandler.updateQuickActions({quickActionHtml:a.html()},
!0)};h.attachSeriesEvent=function(){var f=this;for(i=0;i<this.series.length;i++)a(f.series[i]).on("click",function(c){"-1"==a(c.currentTarget).data("series")?f.$linksContainer.show():f.$linksContainer.hide()})};h.attachShiftTabReturnPoint=function(){var f=this,c=this.series.first().find("button");if(0<c.length)c.on("keydown",function(b){l.isEventKeyCodeShift(b,a.ui.keyCode.TAB)&&(b.stopPropagation(),b.preventDefault(),f.actionsHandler.closeFlyOut())})};h.afterFlyoutReopened=function(){var a=this.series.first().find("button");
l.focus(a)};h.init=function(){this.series=this.$component.find(".pad2 .model-nav li");this.attachSeriesEvent();this.attachShiftTabReturnPoint()};return k});
define("ds2-uxn-multilevel-flyout",["jquery","lazyload","ds2-uxn-navigation-utils"],function(a,l,k){var h=function(a){this.$component=a;this.$flyout=this.$component.find(".ds2-flyout-multilevel");this.$leftContainer=this.$flyout.find(".ds2-flyout-multilevel-left");this.title=this.$leftContainer.find(".ds2-flyout-nav-bar-data-holder").data("title");this.$firstLevelLinks=this.$leftContainer.find(".ds2-first-level-item");this.$rightContainer=this.$flyout.find(".ds2-flyout-multilevel-right");this.$secondLevelContainers=
this.$rightContainer.find(".ds2-second-level-container");this.isExtendedTabletView=this.$component.parents(".ds2-navigation").hasClass("ds2-navigation--extended-tablet-view");this.preselectedSecondLevelLink=this.preselectedFirstLevelLink=null;new l({container:this.$rightContainer[0]});this.init()},f=h.prototype;f.setIdentifier=function(a){this.identifier=a};f.setActionsHandler=function(a){this.actionsHandler=a};f.setPreselectedFirstLevelLink=function(a){this.preselectedFirstLevelLink=a};f.setPreselectedSecondLevelLink=
function(a){this.preselectedSecondLevelLink=a};f.getTitle=function(){return this.title};f.showQuickActions=function(a){a=a.find(".ds2-flyout-quickactions");this.actionsHandler.updateQuickActions({quickActionHtml:a.html()})};f.showCurrentQuickActions=function(){var a=this.$component.find(".ds2-second-level-container_active");this.showQuickActions(a)};f.canHandleBackAction=function(){return"none"!=this.$component.css("display")&&"1"==this.$rightContainer.css("opacity")};f.handleBackAction=function(){this.showLeftContainer(!0);
a(window).trigger("ds2-uxn-navigation-level-3-closed")};f.deactivateAllOtherFirstLevelLinks=function(c){for(i=0;i<this.$firstLevelLinks.length;i++){var b=a(this.$firstLevelLinks[i]);b.attr("data-localId")==c?b.addClass("ds2-first-level-item_active"):b.removeClass("ds2-first-level-item_active")}};f.deactivateAllOtherSecondLevelContainers=function(c,b){for(i=0;i<this.$secondLevelContainers.length;i++){var f=a(this.$secondLevelContainers[i]);f.attr("data-localId")==c?(f.addClass("ds2-second-level-container_active"),
this.showQuickActions(f),b||this.actionsHandler.setFlyoutTitle(f.find(".ds2-flyout-nav-bar-data-holder").html(),!0,!1)):f.removeClass("ds2-second-level-container_active")}};f.animateElement=function(a){a.animate({opacity:0},300);a.animate({opacity:1},80)};f.showLeftContainer=function(a){var b=this;a?this.actionsHandler.setFlyoutTitle(this.title,!1,!0):this.actionsHandler.setFlyoutTitle(this.title,!1,!1);a?(this.$leftContainer.show(),this.$flyout.css(k.getMarginProperty(),"-100%"),this.$flyout.animate(k.getAnimationObject("0"),
400,function(){b.$rightContainer.hide()}),this.$leftContainer.css("opacity",.2),this.$leftContainer.animate({opacity:"1"},400),this.$rightContainer.css("opacity",1),this.$rightContainer.animate({opacity:"0.2"},400)):(this.$flyout.css("margin-left","0"),this.$flyout.css("margin-right","0"),this.$leftContainer.css("opacity",1),this.$rightContainer.css("opacity",.2),this.$leftContainer.show(),this.$rightContainer.hide())};f.showRightContainer=function(){if(this.isMobileLayout()){var a=this;this.$rightContainer.show();
this.$flyout.animate(k.getAnimationObject("-100%"),400,function(){a.$leftContainer.hide();a.$flyout.css(k.getMarginProperty(),0)});this.$leftContainer.animate({opacity:"0.2"},400);this.$rightContainer.animate({opacity:"1"},400)}};f.resetCss=function(){this.$flyout.css("margin-left","0");this.$flyout.css("margin-right","0");this.$leftContainer.css("opacity","1");this.$rightContainer.css("opacity","1");this.$leftContainer.show();this.$rightContainer.show()};f.selectActiveItems=function(a,b){var c=a.attr("data-localId");
a="directLink"==a.attr("data-directLink");this.deactivateAllOtherFirstLevelLinks(c);this.deactivateAllOtherSecondLevelContainers(c,a);b&&b.addClass("ds2-second-level-item-highlight")};f.preselectActiveItems=function(){this.preselectedFirstLevelLink&&this.selectActiveItems(this.preselectedFirstLevelLink,this.preselectedSecondLevelLink)};f.afterFlyoutReopened=function(){k.focus(this.$firstLevelLinks.first())};f.attachEvents=function(){var c=this,b=function(b,f){var d="directLink"==b.attr("data-directLink");
c.selectActiveItems(b);d||c.showRightContainer();"mouseenter"===f.type?a(window).trigger("ds2-uxn-level2-hover",b):"click"===f.type&&(a(window).trigger("ds2-uxn-level2-click",b),d&&(f.preventDefault(),c.openDirectLink(b.find("a"))))},f=function(d){"mouseenter"==d.type&&c.isMobileLayout()||b(a(this),d)},m;for(m=0;m<this.$firstLevelLinks.length;m++){var e=a(this.$firstLevelLinks[m]);e.on("mouseenter",f);e.on("click",f);if(!e.attr("data-directLink"))e.on("keypress",function(d){"13"==(d.keyCode?d.keyCode:
d.which)&&(b(a(this),d),d=a(d.target).attr("data-localId"),d=c.$rightContainer.find('.ds2-second-level-container[data-localId\x3d"'+d+'"]').find(".ds2-second-level-item").first(),k.focus(d))})}for(m=0;m<this.$secondLevelContainers.length;m++)for(f=a(this.$secondLevelContainers[m]).find(".ds2-second-level-item"),j=0;j<f.length;j++)a(f[j]).on("click",function(b){var d=a(this);b.preventDefault();a(window).trigger("ds2-uxn-level3-click",d);c.animateElement(d);c.openDirectLink(d)})};f.openDirectLink=function(a){var b=
a.attr("href"),c=a.attr("target");b&&setTimeout(function(){"_blank"!==c?window.location=b:window.open(b,c)},150)};f.attachFocusOrderEvents=function(){var c=this;this.$firstLevelLinks.first().on("keydown",function(b){k.isEventKeyCodeShift(b,a.ui.keyCode.TAB)&&(b.stopPropagation(),b.preventDefault(),c.actionsHandler.closeFlyOut())});this.$firstLevelLinks.last().on("keydown",function(b){k.isEventKeyCode(b,a.ui.keyCode.TAB)&&(b.stopPropagation(),b.preventDefault(),c.actionsHandler.focusOnClose(c.$firstLevelLinks.last()))});
for(i=0;i<this.$secondLevelContainers.length;i++)a(this.$secondLevelContainers[i]).find(".ds2-second-level-item").first().on("keydown",function(b){k.isEventKeyCodeShift(b,a.ui.keyCode.TAB)&&(b.stopPropagation(),b.preventDefault(),b=a(b.target).closest(".ds2-second-level-container").attr("data-localId"),b=c.$leftContainer.find('.ds2-first-level-item[data-localId\x3d"'+b+'"]'),k.focus(b))})};f.isMobileLayout=function(){return k.isMobileLayout()||k.isExtendedTabletLayout()&&this.isExtendedTabletView};
f.init=function(){this.attachEvents();this.attachFocusOrderEvents()};return h});
define("ds2-uxn-search-flyout",["jquery","ds2-uxn-navigation-utils"],function(a,l){var k=function(a){this.$component=a;this.$input=a.find(".borderless");this.$submit=a.find(".ds2-search-submit");this.$autocomplete=a.find(".autocomplete");this.$suggestionList=a.find(".ds2_flyout-suggestion");this.suggestions=[];this.title=this.$component.find(".ds2-flyout-nav-bar-data-holder").data("title");this.init()},h=k.prototype;h.setSearchLabel=function(a){this.searchLabel=a};h.setSearchUrl=function(a){this.searchUrl=
a};h.setActionsHandler=function(a){this.actionsHandler=a};h.reset=function(){this.$input.val("");this.$submit.hide();this.writeAutocompleteValue(this.searchLabel);this.writeSuggestions("")};h.afterFlyoutReopened=function(){l.focus(this.$input)};h.handleSearchSubmit=function(){var a=this.$input.val();this.goToSearchPage(a)};h.goToSearchPage=function(a){var c=new URL(location.origin+this.searchUrl);a=encodeURIComponent(a);c.hash=btoa('{"q":"'+a+'"}');c.searchParams.set("q",a);window.location.href=c.toString();
0<=window.location.href.indexOf(this.searchUrl)&&location.reload()};h.handleRightArrowPress=function(){var a=this.$input.val(),c=this.$autocomplete.text();2<a.length&&0<c.length&&this.$input.val(c)};h.handleInputChange=function(){var a=this.$input.val();this.handleSubmitVisibility(0<a.length);2<a.length?this.updateSuggestions(a):(this.writeSuggestions(""),0==a.length?this.writeAutocompleteValue(this.searchLabel):this.writeAutocompleteValue(""))};h.handleSubmitVisibility=function(f){f?this.$submit.fadeIn(function(){a(this).css("display",
"inline")}):this.$submit.fadeOut()};h.updateSuggestionList=function(a,c){if(a&&a.results){var b;this.suggestions=[];for(b=0;b<a.results.length;b++)this.suggestions.push(a.results[b].name);this.generateSuggestions(c);0<this.suggestions.length?this.writeAutocompleteValue(this.generateAutocomplete(this.suggestions[0],c)):this.writeAutocompleteValue("")}else this.writeSuggestions("")};h.generateSuggestions=function(a){var c,b="";for(c=0;c<this.suggestions.length;c++){var f=this.suggestions[c],m=this.extractSearchTermCaseSensitive(f,
a);f=f.replace(m,'\x3cspan class\x3d"highlight"\x3e'+m+"\x3c/span\x3e");f='\x3cdiv class\x3d"suggestion" data-search-term\x3d"'+this.suggestions[c]+'" tabindex\x3d"0"\x3e'+f+"\x3c/div\x3e";b+=f}this.writeSuggestions(b)};h.generateAutocomplete=function(a,c){var b=this.extractSearchTermCaseSensitive(a,c);if(0<b.length)a=c+a.substring(c.length+a.indexOf(b)),this.writeAutocompleteValue(a);else return""};h.extractSearchTermCaseSensitive=function(a,c){var b=a.toLowerCase(),f=c.toLowerCase();b=b.indexOf(f);
return 0>b?"":a.substring(b,b+c.length)};h.writeSuggestions=function(a){this.$suggestionList.html(a);this.attachClickEventToSuggestions()};h.attachClickEventToSuggestions=function(){for(var f=this,c=this.$suggestionList.find(".suggestion"),b=0;b<c.length;b++)a(c[b]).on("click",function(){f.goToSearchPage(a(this).attr("data-search-term"))}),a(c[b]).keypress(function(b){(b.keyCode?b.keyCode:b.which)==a.ui.keyCode.ENTER&&f.goToSearchPage(a(this).attr("data-search-term"))})};h.updateSuggestions=function(f){var c=
this,b=this.getGsaSuggestUrl(f);a.get(b,function(a){c.updateSuggestionList(a,f)}).fail(function(){c.updateSuggestionList("")})};h.getGlobalUXNConfig=function(){return"undefined"!==typeof window&&window.uxn?window.uxn:!1};h.getGsaSuggestUrl=function(a){if(a){var c=this.getGlobalUXNConfig(),b="";c&&c.search&&c.search.gsaBaseUrl&&c.search.gsaSuggestUrlContext&&(b=c.search.gsaBaseUrl+c.search.gsaSuggestUrlContext+"?",c.search.gsaClient&&(b+="client\x3d"+c.search.gsaClient+"\x26"),c.search.gsaSite&&(b+=
"site\x3d"+c.search.gsaSite+"\x26"),c.search.maxSuggestions&&(b+="max\x3d"+c.search.maxSuggestions+"\x26"),b+="q\x3d"+encodeURIComponent(a)+"\x26",b+="format\x3drich");return b}};h.writeAutocompleteValue=function(a){this.$autocomplete.text(a)};h.getTitle=function(){return this.title};h.init=function(){var f=this;this.$input.on("input",function(a){f.handleInputChange()});this.$input.on("keydown",function(c){l.isEventKeyCode(c,a.ui.keyCode.RIGHT)?(f.handleRightArrowPress(),f.handleInputChange()):l.isEventKeyCode(c,
a.ui.keyCode.ENTER)?f.handleSearchSubmit():l.isEventKeyCodeShift(c,a.ui.keyCode.TAB)&&(c.stopPropagation(),c.preventDefault(),f.actionsHandler.closeFlyOut())});this.$submit.on("click",function(){f.handleSearchSubmit()});this.$submit.on("keypress",function(c){(c.keyCode?c.keyCode:c.which)==a.ui.keyCode.ENTER&&f.handleSearchSubmit()});this.reset()};return k});
define("ds2-uxn-mybmw-flyout","jquery ds2-uxn-navigation-utils uxn-mybmw-tracking ds2-tracking-checker lazyload ds2-myoverlay-tron-tracking".split(" "),function(a,l,k,h,f,c){function b(a){return window.location.origin+"/"+a.toLowerCase()+"/mybmwweb/api/v1/flyout/linklist"}function q(){var a=location.hostname,b=void 0,d=a.indexOf(".");-1!==d&&(b=a.substring(d));return b}function m(a,b,d,g){var r=new Date,c=r.getTime();r.setTime(c+1E3*d);document.cookie=g?a+"\x3d"+b+" ; path\x3d/; domain\x3d"+g+"; expires\x3d"+
r.toUTCString():a+"\x3d"+b+" ; path\x3d/; expires\x3d"+r.toUTCString()}function e(){var a=window.consentcontroller.api.getCookie("gcdmToken");return null!=a&&""!==a}function d(){window.consentcontroller&&window.consentcontroller.api&&window.consentcontroller.api.deletePersistence("gcdmToken")}function p(){d();m("mybmwUserLogin","",-86400,void 0)}function n(a){return-1<document.cookie.indexOf(a)?(a=(new RegExp(a+"\x3d([^;]+)")).exec(document.cookie),null!=a?unescape(a[1]):null):null}c=function(a,b){this.SALUTATION=
"{salutation}";this.FIRST_NAME="{firstName}";this.LAST_NAME="{lastName}";this.actionsHandler=b;this.$component=a;this.$loggedoutContainer=a.find(".ds2-mybmw-content.ds2-mybmw-loggedout");this.$loggedinContainer=a.find(".ds2-mybmw-content.ds2-mybmw-loggedin");this.$buttons=a.find(".ds2-mybmw-button a");this.$links=a.find(".ds2-mybmw-links a");this.suggestions=[];this.title="MyBMW Web";h.isDigitals2TrackingAvailable()&&(this.tracking=new k(this.$component));this.composeActionLinks();this.init();this.deleteTokenAtLogoutHandler();
a[0]&&new f({container:a[0]})};var g=c.prototype;g.setActionsHandler=function(a){this.actionsHandler=a};g.reset=function(){};g.afterFlyoutReopened=function(){l.focus(this.$component)};g.getTitle=function(){return this.title};g.getUserDataInfo=function(a){var d=a.split("-").pop(),g=this;return{type:"GET",url:b(a),headers:{market:d},complete:function(a,b){g.actionsHandler.displayLogin()}}};g.refreshGcdmToken=function(){this.getCurrentLocales();var b=window.location.origin+"/de-de/mybmw/api/gcdm/refresh",
d=a.Deferred();a.ajax({contentType:"application/json",type:"POST",url:b}).done(function(a){a.data&&a.data.accessToken&&m("gcdmToken",a.data.accessToken,a.data.expiresIn,q());d.resolve(!0)}).fail(function(){d.resolve(!1)});return d.promise()};g.readMyBmwData=function(){function g(b){c.refreshGcdmToken().done(function(g){g&&a.ajax(c.getUserDataInfo(b)).done(function(a){c.trackUserData(a.ucid,a.gcid);c.fillIn(a)}).fail(function(){d();c.displayLoginScreen()});!1===g&&(d(),c.displayLoginScreen());c.hasAdditionalInfo()&&
(m("additionalInfo","",-86400,q()),m("additionalInfo","",-86400,void 0),m("mybmwUserLogin","true",15552E3,void 0))})}var c=this,n=c.getCurrentLocales();e()&&a.ajax(c.getUserDataInfo(n)).done(function(a){c.trackUserData(a.ucid,a.gcid);c.fillIn(a)}).fail(function(a,r){var u=b(n);c.tracking&&c.tracking.trackError(r,u);a=401===a.status?!0:!1;c.isNeededUserToLogin()&&!0===a?g(n):d()});c.isNeededUserToLogin()&&!e()?g(n):c.displayLoginScreen()};g.displayLoginScreen=function(){this.fillInSalutation({});this.actionsHandler.displayLogin()};
g.getCurrentLocales=function(){var b=a(".ds2-navigation-root").attr("lang");void 0===b&&(b=a(a("root-shell")[0].shadowRoot).find(".ds2-navigation-root").attr("lang"));return b};g.trackUserData=function(a,b){try{var d={ucid:CryptoJS.SHA256(a).toString(),gcid:CryptoJS.SHA256(b).toString()};window.dispatchEvent(new CustomEvent("customerData",{detail:d}));console.log("customerData Detail",d)}catch(t){console.log(t)}};g.fillIn=function(a){var b=this;this.fillInSalutation(a);this.fillInLinks(a);setTimeout(function(){b.actionsHandler.showUserLoggedInDot(!0)},
300);this.showLoggedIn()};g.showLoggedIn=function(){this.$loggedoutContainer.hide();this.$loggedinContainer.show()};g.showLoggedOut=function(){this.$loggedoutContainer.show();this.$loggedinContainer.hide()};g.fillInSalutation=function(a){var b=this.$component.find(".salutation").text();b=b.replace(this.SALUTATION,a.Salutation?a.Salutation:"");b=b.replace(this.FIRST_NAME,a.firstName?a.firstName:"");b=b.replace(this.LAST_NAME,a.lastName?a.lastName:"");this.$component.find(".ds2-mybmw-heading.ds2-mybmw-salutation").html(b)};
g.getTrackingLinkId=function(a){return"myb \x3e link to "+a.linkText.toLowerCase().replaceAll("_"," ")};g.fillInLinks=function(a){this.$component.find(".salutation").text();a=a.links;for(var b=this.$component.find(".ds2-mybmw-bullets.ds2-mybmw-links"),d=0;d<a.length;d++){var c='data-tracking-linkid\x3d"nsc \x3e '+a[d].linkName+": "+a[d].linkPath+'"',g="_self";"GARAGE"===a[d].linkText&&(g="_blank");c='\x3cdiv class\x3d"ds2-mybmw-bullet"\x3e    \x3ca data-tracking-linkid\x3d"'+this.getTrackingLinkId(a[d])+
'" data-tracking-regionid\x3d"myb \x3e flyout" href\x3d"'+a[d].linkPath+'" title\x3d"'+a[d].linkName+'" target\x3d"'+g+'" class\x3d"ds2-mybmw-logged-in" '+c+"\x3e"+a[d].linkName+"\x3c/a\x3e\x3c/div\x3e";b.append(c)}this.$links=this.$component.find(".ds2-mybmw-links a")};g.composeActionLinks=function(){var b=a("div[data-login-button] \x3e a")[0];void 0===b&&(b=a(a("root-shell")[0].shadowRoot).find("div[data-login-button] \x3e a")[0]);if(b){var d=new URL(window.location.href),c=d.searchParams;c.set("flyout",
"mybmw");d.search=c.toString();d=btoa(d.toString());d=b.href.replace("targetUrl",d);a(b).attr("href",d)}d=a("div[data-register-button] \x3e a")[0];void 0===d&&(d=a(a("root-shell")[0].shadowRoot).find("div[data-register-button] \x3e a")[0]);d&&(c=btoa(window.location.href),c=d.href.replace("targetUrl",c),a(d).attr("href",c));d=a("div[data-logout-link] \x3e a")[0];void 0===d&&(d=a(a("root-shell")[0].shadowRoot).find("div[data-logout-link] \x3e a")[0]);if(d){c=window.location.href;var g=window.location.pathname.split("/");
2<g.length&&"mybmw"==g[2]&&(c=window.location.origin+"/"+g[1]+"/"+g[2]+"/logout");c=d.href.replace("targetUrl",c);a(d).attr("href",c);a(d).on("click",p)}window.epaas&&window.epaas.api&&(d="\x26epaas_consenttoken\x3d"+window.epaas.api.createConsentToken()+"\x26acid\x3d",c="","object"==typeof s&&s.visitor&&"object"==typeof s.visitor?c=s.visitor.getMarketingCloudVisitorID():-1<document.cookie.indexOf("B52D1CFE5330949C0A490D45%40AdobeOrg")&&(g=document.cookie.split("AMCV_B52D1CFE5330949C0A490D45%40AdobeOrg")[1])&&
(g=g.split(";")[0],g=decodeURIComponent(g),c=g.split("MCMID|")[1].split("|")[0]),b&&(d=b.href+(d+c),a(b).attr("href",d)))};g.deleteTokenAtLogoutHandler=function(){var b=a("div[data-logout-link] \x3e a")[0];void 0===b&&(b=a(a("root-shell")[0].shadowRoot).find("div[data-logout-link] \x3e a")[0]);a(b).on("click",function(a){a.stopPropagation();a.stopImmediatePropagation();window.consentcontroller&&window.consentcontroller.api&&window.consentcontroller.api.deletePersistence("gcdmToken")})};g.fetchMyBmwData=
function(){var a=this;(window.epaas&&window.epaas.api||window).addEventListener("consentcontroller.api.initialized",function(){e()||a.isNeededUserToLogin()?a.readMyBmwData():a.actionsHandler.displayLogin()})};g.isRefreshLoginNeeded=function(){var a=this.getGcdmToken();return(null===a||""===a)&&this.isNeededUserToLogin()};g.hasAdditionalInfo=function(){var a=n("additionalInfo");return void 0!=a&&null!=a&&0<a.length};g.isNeededUserToLogin=function(){return"true"===n("mybmwUserLogin")||this.hasAdditionalInfo()};
g.getGcdmToken=function(){return window.consentcontroller.api.getCookie("gcdmToken")};g.init=function(){var b=this;b.showLoggedOut();a(window).on("login:status:changed",function(){b.fetchMyBmwData()});b.fetchMyBmwData();this.$buttons.first().keydown(function(d){l.isEventKeyCodeShift(d,a.ui.keyCode.TAB)&&(d.stopPropagation(),d.preventDefault(),b.actionsHandler.closeFlyOut())});this.$links.first().keydown(function(d){l.isEventKeyCodeShift(d,a.ui.keyCode.TAB)&&(d.stopPropagation(),d.preventDefault(),
b.actionsHandler.closeFlyOut())});this.reset()};return c});
define("ds2-uxn-navigation","jquery ds2-uxn-search-flyout ds2-uxn-mybmw-flyout ds2-uxn-multilevel-flyout ds2-uxn-allmodels-flyout ds2-uxn-top-navigation-tracking ds2-uxn-navigation-utils ds2-tracking-checker ds2-resize-events focus-visible".split(" "),function(a,l,k,h,f,c,b,q){var m=function(b){this.SEARCH_DESKTOP="#id-search_desktop";this.MYBMW_DESKTOP=".id-user_desktop";this.FLYOUT_SEARCH=".ds2-flyout-search-content";this.FLYOUT_MY_BMW=".ds2-flyout-mybmw-content";this.FLYOUT_ALL_MODELS=".ds2-flyout-all-models-content";
this.FLYOUT_MULTILEVEL=".ds2-flyout-multilevel-content";this.FLYOUT_MY_BMW_PARENT="ds2-flyout-mybmw";this.$component=a(b);this.$menu=this.$component.find(".ds2-navigation-burger");this.$navigationBarRow=this.$component.find(".ds2-navigation-bar-row");this.$actionLinks=this.$component.find(".ds2-action-links");this.$actionLinksContainer=this.$component.find(".ds2-navigation-action-links");this.$logo=this.$component.find(".ds2-navigation-logo");this.$logoWhite=this.$logo.find(".ds2_white_logo");this.$logoGrey=
this.$logo.find(".ds2_grey_logo");this.$shadowLayer=this.$component.find(".ds2-shadow-layer");this.$menuitemscontainer=this.$component.find(".ds2-navigation-bar");this.$menunavigationlinksContainer=this.$menuitemscontainer.find(".ds2-navigation-items");this.$navigationContainer=this.$component.find(".ds2-navigation-container");this.$navigationContainerInner=this.$component.find(".ds2-navigation-container-inner");this.$menunavigationlinks=a(this.$menuitemscontainer).find(".ds2-navigation-link");this.$flyout=
this.$component.find(".ds2-navigation-flyout-layer");this.$flyoutWrapper=this.$flyout.find(".ds2-navigation-flyout-wrapper");this.$flyoutScrollableAreaWrapper=this.$flyoutWrapper.find(".ds2-navigation-flyout-scrollable-wrapper");this.$flyoutScrollableArea=this.$flyoutScrollableAreaWrapper.find(".ds2-navigation-flyout-scrollable");this.$mobileNavBarWrapper=this.$flyoutWrapper.find(".ds2-multilevel-flyout-nav-bar-wrapper");this.$mobileNavBar=this.$mobileNavBarWrapper.find(".ds2-multilevel-flyout-nav-bar");
this.$mobileBack=this.$mobileNavBar.find(".ds2-flyout-back_mobile");this.$flyoutTitle=this.$mobileNavBar.find(".ds2-flyout-title");this.$closeFlyOut=this.$flyoutWrapper.find(".ds2-flyout-close-icon");this.$flyoutContent=this.$flyoutWrapper.find(".ds2-navigation-flyout-content");this.$flyoutSearch=this.$flyoutContent.find(this.FLYOUT_SEARCH);this.$flyoutMyBmw=this.$flyoutContent.find(this.FLYOUT_MY_BMW);this.$flyoutAllModels=this.$flyoutContent.find(this.FLYOUT_ALL_MODELS);this.ds2AllModelsFlyoutJs=
new f(this.$flyoutAllModels);this.ds2AllModelsFlyoutJs.setActionsHandler(this);this.$uxnAasEnabled=!0;this.activeFlyout="";this.$stickQuickActionContainer=this.$flyout.find(".ds2-flyout-stick-quick-actions");this.$stickQuickAction=this.$stickQuickActionContainer.find(".ds2-flyout-quickactions");b=this.$flyoutContent.find(this.FLYOUT_MULTILEVEL);this.multilevelFlyouts={};this.multilevelFlyoutsJs={};for(var d=0;d<b.length;d++){var n=a(b[d]),g=n.attr("data-identifier"),e=new h(n);e.setActionsHandler(this);
e.setIdentifier(g);this.multilevelFlyouts[g]=n;this.multilevelFlyoutsJs[g]=e}q.isDigitals2TrackingAvailable()&&(this.$uxnAasEnabled=!1,new c(this.$component));0===a("root-shell").length&&(this.$uxnAasEnabled=!1);this.activeMenuItem=void 0;b=this.$component.find(".ds2-action-links").find(".myBmwWebEnabled");this.$menuActionLinks=(this.isMyBmwEnabled=b.attr("data-myBmwWebEnabled")&&"true"==b.attr("data-myBmwWebEnabled"))?this.$component.find(".ds2-action-link:not("+this.SEARCH_DESKTOP+","+this.MYBMW_DESKTOP+
")"):this.$component.find(".ds2-action-link:not("+this.SEARCH_DESKTOP+")");this.isBMWMbranded=a("body").hasClass("ds2-branded-bmwm");this.init()},e=m.prototype;e.updateQuickActions=function(a,b){this.$stickQuickAction.html(a.quickActionHtml);a=this.$stickQuickActionContainer.find(".ds2-flyout-stick-multilevel-left");var d=this.$stickQuickActionContainer.find(".ds2-flyout-stick-multilevel-right");b&&1==b?(a.css("width","0"),d.css("width","100%")):(a.css("width","30%"),d.css("width","70%"))};e.showMobileNavigationMenu=
function(){this.toggleSmartBanner("hide");this.showMobileNavigationShadow();this.showNavigationFullBorder(!0);this.$menuitemscontainer.addClass("ds2-navigation-bar-flex")};e.showMobileNavigationMenuWithAnimation=function(){this.showMobileNavigationMenu();this.$menuitemscontainer.css(b.getMarginProperty(),"-100vw");this.$menuitemscontainer.animate(b.getAnimationObject("0"),400);this.$menunavigationlinksContainer.css("opacity","0.2");this.$menunavigationlinksContainer.animate({opacity:"1"},400);this.fadeInShadowLayer()};
e.fadeInShadowLayer=function(){this.$shadowLayer.css("opacity","0");this.$shadowLayer.show();this.$shadowLayer.animate({opacity:"0.4"},400)};e.fadeOutShadowLayer=function(){this.$shadowLayer.animate({opacity:"0"},400);this.$shadowLayer.hide()};e.menuHandler=function(){var b=this,c=function(a){a.stopPropagation();b.markActiveLink(b.$menunavigationlinks[0]);b.makeNavigationMenuWhite(!0);b.showMobileNavigationMenuWithAnimation();b.displayLogo(!1);b.displayBurgerMenu(!1);b.displayActionLinks(!0);b.makePageScrollable(!1)};
a(this.$menu).on("click",function(a){c(event)});a(this.$menu).keypress(function(b){(b.keyCode?b.keyCode:b.which)==a.ui.keyCode.ENTER&&c(b)})};e.hideMobileNavigationMenu=function(){this.$menuitemscontainer.removeClass("ds2-navigation-bar-flex");this.$menuitemscontainer.css("margin-left","0");this.$menuitemscontainer.css("margin-right","0");this.$menunavigationlinksContainer.css("opacity","1")};e.hideMobileNavigationMenuWithAnimation=function(){var a=this;this.$menuitemscontainer.animate(b.getAnimationObject("-100vw"),
400,function(){a.hideMobileNavigationMenu()});this.$menunavigationlinksContainer.animate({opacity:"0.2"},350,function(){a.$menunavigationlinksContainer.css("opacity","1")});this.fadeOutShadowLayer()};e.closeNavigationBarMenu=function(a){this.toggleSmartBanner();this.hideMobileNavigationShadow();this.showNavigationFullBorder(!1);this.makeNavigationMenuWhite(!1);a?this.hideMobileNavigationMenuWithAnimation():this.hideMobileNavigationMenu();this.removeActiveLink();this.addPreselectedFirstLevelItemClass();
this.displayLogo(!0);this.displayBurgerMenu(!0);this.displayActionLinks(!1);this.makePageScrollable(!0)};e.displayLogo=function(a){a?(this.$logo.removeClass("ds2-navigation-logo_hidden"),this.$actionLinksContainer.removeClass("ds2-navigation-action-links--logo-hidden")):this.isMobileLayout()&&(this.$logo.addClass("ds2-navigation-logo_hidden"),this.$actionLinksContainer.addClass("ds2-navigation-action-links--logo-hidden"));0<this.$logoWhite.length&&0<this.$logoGrey.length&&(a=this.$navigationContainer.hasClass("ds2-white-bg"),
this.$logoWhite.removeClass("hidden-logo"),this.$logoGrey.removeClass("hidden-logo"),a?(this.$logoWhite.hide(),this.$logoGrey.show()):(this.$logoWhite.show(),this.$logoGrey.hide()))};e.displayBurgerMenu=function(a){a?(this.$menu.parent().css("visibility","visible"),this.toggleSmartBanner("")):(this.$menu.parent().css("visibility","hidden"),this.toggleSmartBanner("hide"))};e.toggleSmartBanner=function(a){var b=document.querySelector(".smartbanner-android");b={base:document.querySelector(".basecomponent.smartbanner"),
specific:b?b:document.querySelector(".smartbanner-ios")};a="hide"===a?"none":"";for(var d in b)b[d]&&(b[d].style.display=a)};e.displayActionLinks=function(a){a?this.$actionLinks.addClass("ds2-action-links_force-visible"):this.$actionLinks.removeClass("ds2-action-links_force-visible")};e.closeNaviMobile=function(b){b&&b.stopPropagation();this.closeNavigationBarMenu(!0);a(window).trigger("ds2-uxn-navigation-close")};e.closeHandler=function(){var b=this,c=this.$component.find(".ds2-close-menu .icon-close-x");
c.on("click",function(a){b.closeNaviMobile(a)});c.keypress(function(d){(d.keyCode?d.keyCode:d.which)==a.ui.keyCode.ENTER&&b.closeNaviMobile(d)});this.$navigationBarRow.keyup(function(d){(d.keyCode?d.keyCode:d.which)==a.ui.keyCode.ESCAPE&&b.closeNaviMobile(d)})};e.closeAll=function(){this.closeNavigationBarMenu(!1);this.$mobileNavBarWrapper.css("background-color","unset");this.closeFlyOut()};e.navigationLinksHandler=function(){var b=this,c=function(d){var c=a(d.target);c.attr("data-identifier")||(c=
c.parent());b.activeMenuItem=c;d.preventDefault();!b.isMobileLayout()&&c.hasClass("ds2-navigation-active-link")?b.closeFlyOut():c.attr("data-directlink")&&"false"!==c.attr("data-directlink")?b.handleDirectLinkOpen(c):b.handleFlyoutOpen(c);return!1};this.$menunavigationlinks.on("click",function(a){c(a)});this.$menunavigationlinks.keypress(function(a){"13"==(a.keyCode?a.keyCode:a.which)&&c(a)});this.$menuActionLinks.on("click",function(a){a.preventDefault();b.handleDirectLinkOpen(a.target)})};e.handleDirectLinkOpen=
function(b){b=a(b);b.is("a")||(b=b.parent("a"));this.loadTargetPage(b)};e.loadTargetPage=function(a){var b=a.attr("href"),d=a.attr("target");b&&setTimeout(function(){"_blank"!==d?window.location=b:window.open(b,d)},150)};e.handleFlyoutOpen=function(b){this.markActiveLink(b);a(b).attr("data-allModels")?this.openFlyOut(this.FLYOUT_ALL_MODELS):a(b).attr("data-identifier")&&this.openFlyOut(this.FLYOUT_MULTILEVEL,a(b).attr("data-identifier"))};e.removeActiveLink=function(){a.each(this.$menunavigationlinks,
function(b,c){a(c).hasClass("ds2-navigation-active-link")&&a(c).removeClass("ds2-navigation-active-link")})};e.markActiveLink=function(b){this.removeActiveLink();a(b).addClass("ds2-navigation-active-link");this.removePreselectedFirstLevelItemClass()};e.initFlyOut=function(){var b=this;this.$flyout.on("click",function(a){if(a.target!=this)if(b.activeFlyout===b.FLYOUT_MY_BMW&&a.target.className!==b.FLYOUT_MY_BMW_PARENT)b.closeFlyOut();else return;b.closeFlyOut()});this.$flyoutWrapper.keyup(function(d){(d.keyCode?
d.keyCode:d.which)==a.ui.keyCode.ESCAPE&&b.closeFlyOut()});var c=function(){b.closeFlyOut();a(window).trigger("ds2-uxn-navigation-close",a(this))};this.$closeFlyOut.on("click",function(){c()});this.$closeFlyOut.keypress(function(b){(b.keyCode?b.keyCode:b.which)==a.ui.keyCode.ENTER&&c()});var e=function(){b.closeAll();a(window).trigger("ds2-uxn-navigation-close",a(this))};this.$flyout.find(".ds2-close-all").first().click(function(a){e()});this.$flyout.find(".ds2-close-all").keypress(function(b){(b.keyCode?
b.keyCode:b.which)==a.ui.keyCode.ENTER&&e()});var g=function(a){for(var d in b.multilevelFlyoutsJs)if(b.multilevelFlyoutsJs.hasOwnProperty(d)&&(a=b.multilevelFlyoutsJs[d],a.canHandleBackAction&&a.canHandleBackAction())){a.handleBackAction();return}b.closeFlyOut()};this.$mobileBack.click(function(a){g(a)});this.$mobileBack.keypress(function(b){(b.keyCode?b.keyCode:b.which)==a.ui.keyCode.ENTER&&g(b)});var f=this.$component.find(this.SEARCH_DESKTOP);f.on("click",function(d){d.preventDefault();b.openFlyOut(b.FLYOUT_SEARCH);
b.activeMenuItem=a(d.target)});this.ds2SearchFlyout=new l(this.$flyoutSearch);this.ds2SearchFlyout.setSearchLabel(f.attr("title"));this.ds2SearchFlyout.setSearchUrl(f.attr("href"));this.ds2SearchFlyout.setActionsHandler(this);this.isMyBmwEnabled&&(this.myBmwDesktop=this.$component.find(this.MYBMW_DESKTOP),this.myBmwDesktop.on("click",function(d){d.preventDefault();b.openFlyOut(b.FLYOUT_MY_BMW);b.activeMenuItem=a(d.target)}),this.ds2MyBmwFlyout=new k(this.$flyoutMyBmw,this),f=new URLSearchParams(window.location.search),
f.has("flyout")&&"mybmw"===f.get("flyout")&&setTimeout(function(){b.openFlyOut(b.FLYOUT_MY_BMW)},2E3))};e.displayLogin=function(){this.myBmwDesktop.hasClass("ds2-hide-login")&&this.myBmwDesktop.removeClass("ds2-hide-login")};e.showUserLoggedInDot=function(b){var d=this.myBmwDesktop.parent().find(".ds2-mybmw-green-dot");this.isMyBmwEnabled&&b?a(d).css("display","inline"):a(d).css("display","none")};e.openFlyOut=function(d,c){this.makePageScrollable(!1);this.makeNavigationMenuWhite(!0);this.showNavigationShadow();
this.showNavigationFullBorder(!0);this.hideFlyOutsContent();this.displayLogo(!1);this.displayBurgerMenu(!1);this.displayActionLinks(!0);this.switchCloseButtonWithNavBar(this.FLYOUT_SEARCH==d||this.FLYOUT_MY_BMW==d);this.$mobileNavBarWrapper.css("background-color",this.isBMWMbranded?"#000":"#fff");this.setQuickActionVisibility(this.FLYOUT_SEARCH!=d&&this.FLYOUT_MY_BMW!=d);this.setScrollableAreaMaxHeight(this.FLYOUT_ALL_MODELS!=d);this.makeFlyoutSmallAndRightAligned(this.FLYOUT_MY_BMW==d);this.activeFlyout=
d;var e="";if(this.FLYOUT_SEARCH==d){e=this.ds2SearchFlyout.getTitle();this.ds2SearchFlyout.reset();this.$flyoutSearch.show();var g=this.ds2SearchFlyout}else this.FLYOUT_MY_BMW==d?(e=this.ds2MyBmwFlyout.getTitle(),this.$flyoutMyBmw.show(),g=this.ds2MyBmwFlyout):this.FLYOUT_ALL_MODELS==d?(e=this.ds2AllModelsFlyoutJs.getTitle(),this.ds2AllModelsFlyoutJs.showQuickActions(),this.setFlyoutTitle(e,!1,!1),this.$flyoutAllModels.show(),g=this.ds2AllModelsFlyoutJs):this.FLYOUT_MULTILEVEL==d&&(e=this.multilevelFlyoutsJs[c].getTitle(),
this.multilevelFlyoutsJs[c].showCurrentQuickActions(),this.multilevelFlyoutsJs[c].showLeftContainer(!1),this.isMobileLayout()||this.multilevelFlyoutsJs[c].resetCss(),this.multilevelFlyoutsJs[c].preselectActiveItems(),this.multilevelFlyouts[c].show(),g=this.multilevelFlyoutsJs[c]);a(window).trigger("ds2-uxn-navigation-flyout-opened",e);this.isMobileLayout()?(this.$flyout.show(),this.$flyoutScrollableAreaWrapper.css(b.getMarginProperty(),"calc(100vw - 15px)"),this.$flyoutScrollableAreaWrapper.animate(b.getAnimationObject("0"),
400),this.isNavibarMobileExpanded()?(this.$menuitemscontainer.animate(b.getAnimationObject("-100vw"),500),this.$menunavigationlinksContainer.animate({opacity:"0.2"},400)):this.fadeInShadowLayer(),this.FLYOUT_SEARCH==d||this.FLYOUT_MY_BMW==d?this.showMobileNavigationShadow():this.isNavibarMobileExpanded()?this.hideMobileNavigationShadow():this.showMobileNavigationShadow(),this.$mobileNavBar.css("margin-top","-48px"),this.$mobileNavBar.animate({"margin-top":"0"},400)):this.$flyout.slideDown(250,function(){g&&
g.afterFlyoutReopened()})};e.setFlyoutTitle=function(a,c,e){this.$flyoutTitle.html(a);c?(this.$flyoutTitle.css(b.getMarginProperty(),"100vw"),this.$flyoutTitle.animate(b.getAnimationObject("0"),400)):e&&(this.$flyoutTitle.css(b.getMarginProperty(),"-100vw"),this.$flyoutTitle.animate(b.getAnimationObject("0"),400))};e.switchCloseButtonWithNavBar=function(a){a||!this.isMobileLayout()?(this.$closeFlyOut.show(),this.$mobileNavBarWrapper.hide()):(this.$closeFlyOut.hide(),this.$mobileNavBarWrapper.show())};
e.makePageScrollable=function(b){b?a("body").css("overflow","auto"):a("body").css("overflow","hidden")};e.makeNavigationMenuWhite=function(a){a?this.$navigationContainer.addClass(this.isBMWMbranded?"ds2-black-bg":"ds2-white-bg"):this.isStageTeaserPresent()&&this.$navigationContainer.removeClass("ds2-white-bg ds2-black-bg")};e.showNavigationShadow=function(){this.$navigationContainer.addClass("navigation-shadow")};e.hideNavigationShadow=function(){this.$navigationContainer.removeClass("navigation-shadow")};
e.showMobileNavigationShadow=function(){this.$navigationContainer.addClass("navigation-shadow-mobile")};e.hideMobileNavigationShadow=function(){this.$navigationContainer.removeClass("navigation-shadow-mobile")};e.showNavigationFullBorder=function(a){a?this.$navigationContainerInner.addClass("ds2-navigation-container-inner-full-border"):this.$navigationContainerInner.removeClass("ds2-navigation-container-inner-full-border")};e.hideFlyOutsContent=function(){this.$flyoutMyBmw.hide();this.$flyoutSearch.hide();
this.$flyoutAllModels.hide();for(var a in this.multilevelFlyouts)this.multilevelFlyouts.hasOwnProperty(a)&&this.multilevelFlyouts[a].hide()};e.setQuickActionVisibility=function(a){a?this.$stickQuickActionContainer.removeClass("ds2-flyout-stick-quick-actions_hidden"):this.$stickQuickActionContainer.addClass("ds2-flyout-stick-quick-actions_hidden")};e.setScrollableAreaMaxHeight=function(a){a?this.$flyoutWrapper.addClass("ds2-navigation-flyout-wrapper_max-height"):this.$flyoutWrapper.removeClass("ds2-navigation-flyout-wrapper_max-height")};
e.makeFlyoutSmallAndRightAligned=function(a){a?(this.$flyoutScrollableAreaWrapper.addClass("ds2-navigation-flyout-scrollable-wrapper-right-aligned"),this.$flyoutScrollableArea.addClass("ds2-navigation-flyout-scrollable-right-aligned")):(this.$flyoutScrollableAreaWrapper.removeClass("ds2-navigation-flyout-scrollable-wrapper-right-aligned"),this.$flyoutScrollableArea.removeClass("ds2-navigation-flyout-scrollable-right-aligned"))};e.closeFlyOut=function(){this.activeMenuItem&&(b.focus(this.activeMenuItem),
this.activeMenuItem=void 0);this.activeFlyout="";this.hideNavigationShadow();var a=this;this.isMobileLayout()?(this.isNavibarMobileExpanded()?(this.$menuitemscontainer.css(b.getMarginProperty(),"calc(-100vw + 15px)"),this.$menuitemscontainer.animate(b.getAnimationObject("0"),400),this.$menunavigationlinksContainer.animate({opacity:"1"},400),this.showMobileNavigationShadow(),this.showNavigationFullBorder(!0)):(this.fadeOutShadowLayer(),this.hideMobileNavigationShadow(),this.showNavigationFullBorder(!1)),
this.$flyoutScrollableAreaWrapper.animate(b.getAnimationObject("100vw"),450,function(){a.$flyout.hide();a.$flyoutScrollableAreaWrapper.css(b.getMarginProperty(),"0");a.afterCloseFlyout()}),this.$mobileNavBar.animate({"margin-top":"-48px"},400)):(this.showNavigationFullBorder(!1),this.$flyout.slideUp(300,function(){a.afterCloseFlyout()}))};e.afterCloseFlyout=function(){this.hideFlyOutsContent();var a=this.isNavibarMobileExpanded();a||(this.makePageScrollable(!0),this.makeNavigationMenuWhite(!1),this.displayLogo(!0),
this.displayBurgerMenu(!0));this.displayActionLinks(a);this.removeActiveLink();this.addPreselectedFirstLevelItemClass();this.setQuickActionVisibility(!1);this.$stickQuickAction.html("")};e.isNavibarMobileExpanded=function(){return this.$menuitemscontainer.hasClass("ds2-navigation-bar-flex")};e.initQuickActionsClick=function(){var b=this;b.$component.on("click",".ds2-uxn-navigation-quick-action",function(d){d.preventDefault();d=a(this);a(window).trigger("ds2-uxn-nav-quickaction-click",d);b.loadTargetPage(d)})};
e.closeAllAndClean=function(){this.closeNavigationBarMenu(!1);this.$mobileNavBarWrapper.css("background-color","unset");this.$menuitemscontainer.css("margin-left","0");this.$menuitemscontainer.css("margin-right","0");this.$menunavigationlinksContainer.css("opacity","1");this.$shadowLayer.hide();this.$flyout.hide();this.$flyoutScrollableAreaWrapper.css("margin-left","0");this.$flyoutScrollableAreaWrapper.css("margin-right","0");this.afterCloseFlyout()};e.onResize=function(){var a=this.isMobileLayout();
this.isMobileLayoutActive!=a&&this.closeAllAndClean();this.isMobileLayoutActive=a};e.isStageTeaserPresent=function(){return"undefined"!==typeof window&&window.uxn&&window.uxn.stage};e.getCurrentPage=function(){var b=a("script#ds2-page-context").html();return b?JSON.parse(b)["current-page"]:""};e.cleanHtmlExtension=function(a){return 0<a.lastIndexOf(".html")?a.substring(0,a.lastIndexOf(".html")):a};e.isPathMatching=function(a,b){return-1!==a.indexOf(this.cleanHtmlExtension(b))};e.addPreselectedFirstLevelItemClass=
function(){this.preselectedFirstLevelItem&&this.preselectedFirstLevelItem.addClass("ds2-navigation-link-preselected")};e.removePreselectedFirstLevelItemClass=function(){this.preselectedFirstLevelItem&&this.preselectedFirstLevelItem.removeClass("ds2-navigation-link-preselected")};e.preselectMenuItems=function(){this.preselectedFirstLevelItem=null;var b=this.getCurrentPage();if(b){for(var c=this.$menunavigationlinksContainer.find(".ds2-navigation-item .ds2-navigation-link"),e=0;e<c.length;e++)if(a(c[e]).attr("data-directlink")&&
this.isPathMatching(b,a(c[e]).attr("data-path"))){this.preselectedFirstLevelItem=a(c[e]);this.addPreselectedFirstLevelItemClass();break}if(!this.preselectedFirstLevelItem)for(e=0;e<c.length;e++)if(!a(c[e]).attr("data-directlink")){var g=a(c[e]).attr("data-identifier"),f=this.multilevelFlyouts[g];if(f)for(var m=f.find(".ds2-first-level-item[data-directlink\x3d'directLink']"),v=0;v<m.length;v++)if(f=a(m[v]).find("a:first"),this.isPathMatching(b,a(f).attr("data-path"))){this.preselectedFirstLevelItem=
a(c[e]);this.addPreselectedFirstLevelItemClass();var q=this.multilevelFlyoutsJs[g];q.setPreselectedFirstLevelLink(a(m[v]));break}}if(!this.preselectedFirstLevelItem)for(e=0;e<c.length;e++)if(!a(c[e]).attr("data-directlink")&&(g=a(c[e]).attr("data-identifier"),f=this.multilevelFlyouts[g]))for(m=f.find(".ds2-first-level-item:not([data-directlink\x3d'directLink'])"),v=0;v<m.length;v++)for(var h=a(m[v]).attr("data-localid"),l=f.find(".ds2-second-level-container"),k=0;k<l.length;k++)if(h==a(l[k]).attr("data-localid"))for(var x=
a(l[k]).find("a.ds2-second-level-item"),w=0;w<x.length;w++)if(this.isPathMatching(b,a(x[w]).attr("data-path"))){this.preselectedFirstLevelItem=a(c[e]);this.addPreselectedFirstLevelItemClass();q=this.multilevelFlyoutsJs[g];q.setPreselectedFirstLevelLink(a(m[v]));q.setPreselectedSecondLevelLink(a(x[w]));break}if(!this.preselectedFirstLevelItem)for(e=0;e<c.length;e++)if(a(c[e]).attr("data-allmodels")&&a(c[e]).attr("data-path")&&this.isPathMatching(b,a(c[e]).attr("data-path"))){this.preselectedFirstLevelItem=
a(c[e]);this.addPreselectedFirstLevelItemClass();break}}};e.handleFocusOrder=function(){var c=this;this.$closeFlyOut.keydown(function(d){if(b.isEventKeyCode(d,a.ui.keyCode.TAB))return d.stopPropagation(),d.preventDefault(),!0;if(c.closeReturnElement&&b.isEventKeyCodeShift(d,a.ui.keyCode.TAB))return d.stopPropagation(),d.preventDefault(),b.focus(c.closeReturnElement),c.closeReturnElement=void 0,!0})};e.focusOnClose=function(a){b.focus(this.$closeFlyOut);this.closeReturnElement=a};e.init=function(){var b=
this;this.menuHandler();this.closeHandler();this.navigationLinksHandler();this.initFlyOut();this.initQuickActionsClick();this.isMobileLayoutActive=this.isMobileLayout();b=this;a(window.digitals2.resizeEvents).on("ds2ResizeSmall ds2ResizeMedium ds2ResizeLarge",function(a){b.onResize()});this.preselectMenuItems();this.handleFocusOrder();window.addEventListener("hashchange",function(){b.closeFlyOut();b.isNavibarMobileExpanded()&&b.closeNaviMobile()},!1);this.uxnAasChangeStyles(this.$uxnAasEnabled)};
e.uxnAasChangeStyles=function(a){a&&(console.log("Uxn As a Service is added and the styles are changed"),this.$navigationContainer.addClass(this.isBMWMbranded?"ds2-black-bg":"ds2-white-bg"),this.displayLogo(!0))};e.isMobileLayout=function(){return b.isMobileLayout()||b.isExtendedTabletLayout()&&this.$component.hasClass("ds2-navigation--extended-tablet-view")};return m});
define("ds2-uxn-top-navigation-tracking",["jquery"],function(a){var l={componentInfo:{componentID:"",componentName:"user_centric_navigation",componentHeadline:"na"},category:{primaryCatergory:"Navigation",subCategory01:"na"},attributes:{visible:"true",variant:"1 column"}},k={eventInfo:{eventName:"",eventAction:"click",eventPoints:"na",cause:"default",target:"na",effect:"Click",element:"Other"},category:{primaryCategory:l.category.primaryCatergory,subCategory01:l.category.subCategory01,mmdr:"na"},
attributes:{relatedComponent:{}}},h=[],f=function(a){this.$component=a;l.componentInfo.componentID=a.attr("data-component-id");k.attributes.relatedComponent=l;this.attachEvents();this.initTrackingComponent(l)},c=f.prototype;c.attachEvents=function(){this.attachLevel1NavEvents();this.attachLevel2NavEvents();this.attachLevel3NavEvents();this.attachQuickActionsNavEvents();this.attachCloseNavigationEvents()};c.attachLevel1NavEvents=function(){function b(b){return function(c){c.preventDefault();c=a(c.target);
var d=f.isLinkInternal(c);f.trackEvent({eventInfo:{eventName:f.getElementText(c,"L1"),eventAction:f.getEventAction(d,"L1"),cause:f.getElementText(c,"L1"),element:b?b:k.eventInfo.element},category:{eventType:f.getEventType(d)}},f.getSatelliteName(d))}}function c(b){return function(c){c.preventDefault();c=a(c.target);f.trackEvent({eventInfo:{eventName:f.getElementText(c,"L1"),eventAction:"Open navigation",cause:f.getElementText(c,"L1"),element:b?b:k.eventInfo.element},category:{eventType:"triggered"}},
"open_navigation");var d=c.attr("data-identifier")||c.parent().attr("data-identifier");if(d&&(d=f.$component.find('.ds2-flyout-multilevel-content[data-identifier\x3d"'+d+'"]').find(".ds2-first-level-item.ds2-first-level-item_active"),0<d.length)){d=f.getElementText(d,"L2");var e=f.getElementText(c,"L1");f.trackEvent({eventInfo:{eventName:e+" | "+d,eventAction:"Open navigation",cause:f.getElementText(c,"L1"),element:b?b:k.eventInfo.element},category:{eventType:"triggered"}},"open_navigation")}}}var f=
this,e=this.$component.find(".ds2-navigation-bar"),d=this.$component.find(".ds2-navigation-action-links");e.find('.ds2-navigation-link:not([data-directlink\x3d"true"])').on("click",c());e.find('.ds2-navigation-link[data-directlink\x3d"true"]').on("click",b());d.find(".ds2-action-link:not(#id-search_desktop)").on("click",b("Icon"));d.find("#id-search_desktop").on("click",c("Icon"))};c.attachLevel2NavEvents=function(){var b=this,c=null,f=null;a(window).on("ds2-uxn-level2-hover",function(e,d){var m=
a(d);b.isL2DirectLink(m)||(e=m.attr("data-localId"),c&&clearTimeout(c),f!==e&&(f=e,c=setTimeout(function(){m.parents(".ds2-flyout-multilevel").find('.ds2-flyout-multilevel-right .ds2-second-level-container[data-localid\x3d"'+m.attr("data-localid")+'"]').is(":visible")&&(b.pushLevel2ToLevelStack(b.getElementText(m,"L2")),b.trackLevel2Event(m,"hover"))},3E3)))});a(window).on("ds2-uxn-level2-click",function(e,d){e=a(d);b.isL2DirectLink(e)?b.trackLevel2DirectLinkEvent(e.find("a")):(b.pushLevel2ToLevelStack(b.getElementText(e,
"L2")),b.trackLevel2Event(e,"click"));clearTimeout(c)})};c.trackLevel2Event=function(a,c){var b=this.getElementText(a,"L2");a=this.getLevel1SelectedItemName(a);this.trackEvent({eventInfo:{eventName:a+" | "+b,eventAction:"Open navigation",cause:a,element:"Text link",effect:c},category:{eventType:"triggered"}},"open_navigation")};c.trackLevel2DirectLinkEvent=function(a){var b=this.isLinkInternal(a),c=this.getElementText(a,"L2");a=this.getLevel1SelectedItemName(a);this.trackEvent({eventInfo:{eventName:a+
" | "+c,eventAction:this.getEventAction(b,"L1"),cause:a},category:{eventType:this.getEventType(b)}},this.getSatelliteName(b))};c.attachLevel3NavEvents=function(){var b=this;a(window).on("ds2-uxn-level3-click",function(c,f){var e=a(f);c=b.isLinkInternal(e);f=b.getElementText(e,"L3");var d=b.getLevel1SelectedItemName(e);e=b.getLevel2SelectedItemName(e);b.trackEvent({eventInfo:{eventName:d+" | "+e+" | "+f,eventAction:b.getEventAction(c,"L1"),cause:d+" | "+e},category:{eventType:b.getEventType(c)}},b.getSatelliteName(c))})};
c.attachQuickActionsNavEvents=function(){var b=this;a(window).on("ds2-uxn-nav-quickaction-click",function(c,f){var e=a(f);c=b.isLinkInternal(e);f=b.getElementText(e,"Quick Actions: ");e=e.attr("data-nav-item");b.trackEvent({eventInfo:{eventName:e+" | "+f,eventAction:b.getEventAction(c,"L1"),cause:e},category:{eventType:b.getEventType(c)}},b.getSatelliteName(c))})};c.resetLevelStack=function(a){h=[a]};c.pushLevel2ToLevelStack=function(a){if(2<=h.length)for(;2<=h.length;)this.popLevelStack();this.pushToLevelStack(a)};
c.pushToLevelStack=function(a){h.push(a)};c.popLevelStack=function(){h.pop()};c.getPopStackCause=function(){if(!h)return"";for(var a="",c=0;c<h.length;c++)a+=h[c],c<h.length-1&&(a+=" | ");return a};c.attachCloseNavigationEvents=function(){var b=this;a(window).on("ds2-uxn-navigation-flyout-opened",function(a,c){b.resetLevelStack("L1 "+c)});a(window).on("ds2-uxn-navigation-level-3-closed",function(a){b.popLevelStack()});a(window).on("ds2-uxn-navigation-close",function(a,c){a=c?b.getPopStackCause():
"Mobile menu first screen";b.trackEvent({eventInfo:{eventName:"L1 Close",eventAction:"Close navigation",cause:a},category:{eventType:"triggered"}},"close_navigation")})};c.getElementText=function(a,c){var b=a.text().trim();return b?c+" "+b:c+" "+a.parent().text().trim()};c.getEventType=function(a){return a?"delayed":"triggered"};c.getSatelliteName=function(a){return a?"internal_click":"outbound_click"};c.getEventAction=function(a){return a?"Internal click":"Outbound click"};c.isLinkInternal=function(a){var b=
a;a.is("a")||(b=a.parent("a"));a=b.attr("href");return!a.match(/^(http[s]?:\/\/(www\.)?|ftp:\/\/(www\.)?|www\.){1}([0-9A-Za-z-\.@:%_+~#=]+)+((\.[a-zA-Z]{2,3})+)(\/(.)*)?(\?(.)*)?/)||-1!==a.indexOf(window.location.host)};c.getLevel1SelectedItemName=function(a){a=a.parents(".ds2-flyout-multilevel-content").attr("data-identifier");a=this.$component.find('.ds2-navigation-items .ds2-navigation-active-link[data-identifier\x3d"'+a+'"]');return this.getElementText(a,"L1")};c.getLevel2SelectedItemName=function(a){a=
a.parents(".ds2-flyout-multilevel-content").find(".ds2-first-level-item.ds2-first-level-item_active");return this.getElementText(a,"L2")};c.isL2DirectLink=function(a){return"directLink"===a.attr("data-directLink")};c.trackEvent=function(b,c){var f=a.extend(!0,{},b,{eventInfo:{timeStamp:Date.now().toString()}}),e=window.digitals2&&window.digitals2.tracking.api;e&&(f.category&&"delayed"===f.category.eventType?(f=a.extend(!0,{},k,b,{eventInfo:{timeStamp:Date.now().toString()}}),e.eventCookieSave(f)):
(e.addEventTracking(k,f,0),e.satelliteTrack(c)))};c.initTrackingComponent=function(a){var b=window.digitals2&&window.digitals2.tracking.api;b&&b.initComponentTracking(a,0)};return f});
define("uxn-mybmw-tracking",["jquery"],function(a){var l={componentInfo:{componentID:"nsc \x3e native in-page \x3e mybmw-login-overlay",componentName:"mybmw-login-overlay",componentHeadline:"na",componentVersion:"1.0"},category:{primaryCatergory:"nsc website",subCategory01:"navigation",componentType:"native in-page"},attributes:{visible:"true",variant:"1 column",touchpoint:"web"}},k={eventInfo:{eventName:"interaction",eventAction:"open content",eventPoints:"na",cause:"default",target:"na",element:"Other"},
category:{primaryCategory:"mybmw-login-overlay",subCategory01:"navigation",mmdr:"na",eventType:"triggered"},attributes:{requestedURL:"na",search:{label:"na"},linkedComponent:{componentInfo:{componentID:l.componentInfo.componentID}},linkedPage:{pageInfo:{pageID:"na"}},linkedProduct:{productInfo:{productID:"na"}}}},h=function(a){this.$component=a;this.attachEvents();this.initTrackingComponent(l)},f=h.prototype;f.attachEvents=function(){this.attachLevel1NavEvent();this.attachActionEvents()};f.attachLevel1NavEvent=
function(){var c=this;this.$component.closest(".ds2-navigation-root").find("a.id-user_desktop").on("click",function(){return function(b){b.preventDefault();a(b.target);c.trackEvent({eventInfo:{type:"success",eventAction:"open content",effect:"nsc \x3e fly out opened"},attributes:{requestedURL:window.location.href}},"open_navigation")}}())};f.attachActionEvents=function(){function c(c,e){return function(d){d.preventDefault();var g=a(d.target);"A"!=g.prop("tagName")&&(g=g.closest("A"));b.trackEvent({eventInfo:{type:"ux",
eventAction:c,effect:e},attributes:{requestedURL:g.attr("href")}},"open_navigation");setTimeout(function(){window.location.href=g.attr("href")},1E3)}}var b=this,f=this.$component.find(".myBmwLogin"),h=this.$component.find(".myBmwRegister"),e=this.$component.find(".myBmwLogout");f.on("click",c("outbound click","nsc \x3e login attempt"));h.on("click",c("outbound click","nsc \x3e register attempt"));e.on("click",c("internal click","nsc \x3e logout"))};f.trackError=function(a,b){this.trackEvent({eventInfo:{eventName:"error",
type:"backend 3rd party",eventAction:"call",effect:"nsc \x3e load mybmw links",cause:a},category:{subCategory01:a,subCategory02:"MyBMW",componentType:"native in-page"},attributes:{requestedURL:b}},"open_navigation")};f.trackEvent=function(c,b){c=a.extend(!0,{},c,{eventInfo:{timeStamp:Date.now().toString()}});var f=window.digitals2&&window.digitals2.tracking.api;f&&(f.addEventTracking(k,c,0),f.satelliteTrack(b))};f.initTrackingComponent=function(a){var b=window.digitals2&&window.digitals2.tracking.api;
b&&b.initComponentTracking(a,0)};return h});
var CryptoJS=CryptoJS||function(a,l){var k={},h=k.lib={},f=function(){},c=h.Base={extend:function(a){f.prototype=this;var b=new f;a&&b.mixIn(a);b.hasOwnProperty("init")||(b.init=function(){b.$super.init.apply(this,arguments)});b.init.prototype=b;b.$super=this;return b},create:function(){var a=this.extend();a.init.apply(a,arguments);return a},init:function(){},mixIn:function(a){for(var b in a)a.hasOwnProperty(b)&&(this[b]=a[b]);a.hasOwnProperty("toString")&&(this.toString=a.toString)},clone:function(){return this.init.prototype.extend(this)}},
b=h.WordArray=c.extend({init:function(a,b){a=this.words=a||[];this.sigBytes=b!=l?b:4*a.length},toString:function(a){return(a||m).stringify(this)},concat:function(a){var b=this.words,c=a.words,d=this.sigBytes;a=a.sigBytes;this.clamp();if(d%4)for(var e=0;e<a;e++)b[d+e>>>2]|=(c[e>>>2]>>>24-e%4*8&255)<<24-(d+e)%4*8;else if(65535<c.length)for(e=0;e<a;e+=4)b[d+e>>>2]=c[e>>>2];else b.push.apply(b,c);this.sigBytes+=a;return this},clamp:function(){var b=this.words,c=this.sigBytes;b[c>>>2]&=4294967295<<32-
c%4*8;b.length=a.ceil(c/4)},clone:function(){var a=c.clone.call(this);a.words=this.words.slice(0);return a},random:function(c){for(var d=[],e=0;e<c;e+=4)d.push(4294967296*a.random()|0);return new b.init(d,c)}}),q=k.enc={},m=q.Hex={stringify:function(a){var b=a.words;a=a.sigBytes;for(var c=[],d=0;d<a;d++){var e=b[d>>>2]>>>24-d%4*8&255;c.push((e>>>4).toString(16));c.push((e&15).toString(16))}return c.join("")},parse:function(a){for(var c=a.length,d=[],e=0;e<c;e+=2)d[e>>>3]|=parseInt(a.substr(e,2),16)<<
24-e%8*4;return new b.init(d,c/2)}},e=q.Latin1={stringify:function(a){var b=a.words;a=a.sigBytes;for(var c=[],d=0;d<a;d++)c.push(String.fromCharCode(b[d>>>2]>>>24-d%4*8&255));return c.join("")},parse:function(a){for(var c=a.length,d=[],e=0;e<c;e++)d[e>>>2]|=(a.charCodeAt(e)&255)<<24-e%4*8;return new b.init(d,c)}},d=q.Utf8={stringify:function(a){try{return decodeURIComponent(escape(e.stringify(a)))}catch(r){throw Error("Malformed UTF-8 data");}},parse:function(a){return e.parse(unescape(encodeURIComponent(a)))}},
p=h.BufferedBlockAlgorithm=c.extend({reset:function(){this._data=new b.init;this._nDataBytes=0},_append:function(a){"string"==typeof a&&(a=d.parse(a));this._data.concat(a);this._nDataBytes+=a.sigBytes},_process:function(c){var d=this._data,e=d.words,f=d.sigBytes,g=this.blockSize,h=f/(4*g);h=c?a.ceil(h):a.max((h|0)-this._minBufferSize,0);c=h*g;f=a.min(4*c,f);if(c){for(var l=0;l<c;l+=g)this._doProcessBlock(e,l);l=e.splice(0,c);d.sigBytes-=f}return new b.init(l,f)},clone:function(){var a=c.clone.call(this);
a._data=this._data.clone();return a},_minBufferSize:0});h.Hasher=p.extend({cfg:c.extend(),init:function(a){this.cfg=this.cfg.extend(a);this.reset()},reset:function(){p.reset.call(this);this._doReset()},update:function(a){this._append(a);this._process();return this},finalize:function(a){a&&this._append(a);return this._doFinalize()},blockSize:16,_createHelper:function(a){return function(b,c){return(new a.init(c)).finalize(b)}},_createHmacHelper:function(a){return function(b,c){return(new n.HMAC.init(a,
c)).finalize(b)}}});var n=k.algo={};return k}(Math);
(function(a){var l=CryptoJS,k=l.lib,h=k.WordArray,f=k.Hasher;k=l.algo;for(var c=[],b=[],q=function(a){return 4294967296*(a-(a|0))|0},m=2,e=0;64>e;){a:{var d=m;for(var p=a.sqrt(d),n=2;n<=p;n++)if(!(d%n)){d=!1;break a}d=!0}d&&(8>e&&(c[e]=q(a.pow(m,.5))),b[e]=q(a.pow(m,1/3)),e++);m++}var g=[];k=k.SHA256=f.extend({_doReset:function(){this._hash=new h.init(c.slice(0))},_doProcessBlock:function(a,c){for(var d=this._hash.words,e=d[0],f=d[1],h=d[2],l=d[3],k=d[4],m=d[5],n=d[6],p=d[7],r=0;64>r;r++){if(16>r)g[r]=
a[c+r]|0;else{var q=g[r-15],u=g[r-2];g[r]=((q<<25|q>>>7)^(q<<14|q>>>18)^q>>>3)+g[r-7]+((u<<15|u>>>17)^(u<<13|u>>>19)^u>>>10)+g[r-16]}q=p+((k<<26|k>>>6)^(k<<21|k>>>11)^(k<<7|k>>>25))+(k&m^~k&n)+b[r]+g[r];u=((e<<30|e>>>2)^(e<<19|e>>>13)^(e<<10|e>>>22))+(e&f^e&h^f&h);p=n;n=m;m=k;k=l+q|0;l=h;h=f;f=e;e=q+u|0}d[0]=d[0]+e|0;d[1]=d[1]+f|0;d[2]=d[2]+h|0;d[3]=d[3]+l|0;d[4]=d[4]+k|0;d[5]=d[5]+m|0;d[6]=d[6]+n|0;d[7]=d[7]+p|0},_doFinalize:function(){var b=this._data,c=b.words,d=8*this._nDataBytes,e=8*b.sigBytes;
c[e>>>5]|=128<<24-e%32;c[(e+64>>>9<<4)+14]=a.floor(d/4294967296);c[(e+64>>>9<<4)+15]=d;b.sigBytes=4*c.length;this._process();return this._hash},clone:function(){var a=f.clone.call(this);a._hash=this._hash.clone();return a}});l.SHA256=f._createHelper(k);l.HmacSHA256=f._createHmacHelper(k)})(Math);